### ISSUE TITLE
Unable to run it with Bun, in TS

### ISSUE THREAD

**Issue by YuriVivaldi** [loloToster/openweather-api-node#9]
**Describe the bug**
The class OpenWeatherAPI constructor is returned as undefined

**To Reproduce**
run the [example](https://github.com/loloToster/openweather-api-node/blob/master/examples/using-options.js) with [bun](https://bun.sh/)
I tried to use the import syntax, in TS, but it doesn't work
In JS with node it works fine

**Expected behavior**
The class should just instantiate and the example should run

**Screenshots**
![Code_SmTXnQUaA5](https://github.com/loloToster/openweather-api-node/assets/87307524/a51a93a8-d498-4fd4-abbb-c2c08b7f2cf8)

**Please complete the following information:**
Bun version: 1.1.9
openweather-api-node version: 3.1.2

**Additional context**
I'm using Bun as the runtime...is that the problem?

**Comment by Jarred-Sumner** [comment]
The bug is here, it's using `Object.defineProperty(exports, "__esModule", { value: true });` which is leading to the default export in the .mjs wrapper being `undefined`

<img width="796" alt="image" src="https://github.com/loloToster/openweather-api-node/assets/709451/74fa86f7-6b32-48f5-85fb-2575f7fe97e0">

**Comment by loloToster** [comment]
Thanks for reporting this issue! It should be fixed thanks to Jarred in the newest version.
